import { RISK_MODE_LABELS } from './appPresentationConfig'
import type {
  BuildHeaderStatusPanelsPropsOptions,
  RuntimeSettingsPanelProps,
} from './buildHeaderStatusPanelsTypes'

export const buildRuntimeSettingsPanelProps = ({
  mode,
  nowHHMM,
  onModeChange,
  useMockLocation,
  onUseMockLocationChange,
  locationLabel,
  radiusMeters,
  onRadiusChange,
  riskMode,
  onRiskModeChange,
  showZones,
  onShowZonesChange,
  showIntersectionZones,
  onShowIntersectionZonesChange,
  showCrosswalkZones,
  onShowCrosswalkZonesChange,
  showParkingSpaces,
  onShowParkingSpacesChange,
  parkingSpaceCount,
  actionFilteredMarkedSpaceSegmentCount,
  markedSpacesOnly,
  onMarkedSpacesOnlyChange,
  actionFilter,
  actionFilterHiddenCount,
  onActionFilterChange,
  hideReportedIllegal,
  illegalFeedbackHiddenCount,
  onHideReportedIllegalChange,
  showInferredCandidates,
  onShowInferredCandidatesChange,
  includeInferred,
  onIncludeInferredChange,
}: BuildHeaderStatusPanelsPropsOptions): RuntimeSettingsPanelProps => ({
  mode,
  nowHHMM,
  onModeChange,
  useMockLocation,
  onUseMockLocationChange,
  locationLabel,
  radiusMeters,
  onRadiusChange,
  riskMode,
  riskModeLabels: RISK_MODE_LABELS,
  onRiskModeChange,
  showZones,
  onShowZonesChange,
  showIntersectionZones,
  onShowIntersectionZonesChange,
  showCrosswalkZones,
  onShowCrosswalkZonesChange,
  showParkingSpaces,
  onShowParkingSpacesChange,
  parkingSpaceCount,
  actionFilteredMarkedSpaceSegmentCount,
  markedSpacesOnly,
  onMarkedSpacesOnlyChange,
  actionFilter,
  actionFilterHiddenCount,
  onActionFilterChange,
  hideReportedIllegal,
  illegalFeedbackHiddenCount,
  onHideReportedIllegalChange,
  showInferredCandidates,
  onShowInferredCandidatesChange,
  includeInferred,
  onIncludeInferredChange,
})
