import {
  formatDistanceMeters,
  formatParkingSpaceCount,
} from './displayFormatting'
import type {
  PrimaryControlsProps,
} from './buildPrimaryControlsPropsTypes'
import type { BuildHeaderSearchPanelsPropsOptions } from './buildHeaderSearchPanelsTypes'

export const buildPrimaryControlsProps = ({
  activeView,
  onActiveViewChange,
  onMapPrefetch,
  datasetId,
  datasetOptions,
  onDatasetIdChange,
  filterInputRef,
  filterQuery,
  onFilterQueryChange,
  onFilterInputKeyDown,
  segmentFilterSuggestions,
  selectedId,
  onSegmentSuggestionKeyDown,
  onSelectSegmentSuggestion,
  registerSegmentSuggestionRef,
  filteredSegmentCount,
  totalSegmentCount,
  hasActiveFilters,
  activeFilterChips,
  onResetViewFilters,
  onClearActiveFilter,
}: BuildHeaderSearchPanelsPropsOptions): PrimaryControlsProps => ({
  activeView,
  onActiveViewChange,
  onMapPrefetch,
  datasetId,
  datasetOptions,
  onDatasetIdChange,
  filterInputRef,
  filterQuery,
  onFilterQueryChange,
  onFilterInputKeyDown,
  segmentFilterSuggestions,
  selectedId,
  onSegmentSuggestionKeyDown,
  onSelectSegmentSuggestion,
  registerSegmentSuggestionRef,
  formatDistanceMeters,
  formatParkingSpaceCount,
  filteredSegmentCount,
  totalSegmentCount,
  hasActiveFilters,
  activeFilterChips,
  onResetViewFilters,
  onClearActiveFilter,
})
