import { FAVORITE_ROLE_LABELS } from './displayFormatting'
import type {
  AddressSearchPanelProps,
} from './buildAddressSearchPanelPropsTypes'
import type { BuildHeaderSearchPanelsPropsOptions } from './buildHeaderSearchPanelsTypes'

export const buildAddressSearchPanelProps = ({
  addressInputRef,
  addressQuery,
  geocodeStatus,
  geocodeError,
  geocodeResultsCount,
  activeDistanceLabel,
  locationStatus,
  searchLocationLabel,
  searchAnchor,
  searchActionCount,
  isPinnedFavorite,
  pinnedFavoriteRole,
  favoriteAddresses,
  quickFavoriteAddresses,
  visibleGeocodeResults,
  visibleFavoriteAddresses,
  visibleRecentAddresses,
  favoriteAddressOffset,
  recentAddressOffset,
  registerSearchActionRef,
  onAddressQueryChange,
  onAddressInputKeyDown,
  onAddressSearch,
  onClearAddressSearch,
  onToggleFavoriteAddress,
  onSetFavoriteAddressRole,
  onClearFavoriteAddressRole,
  onChooseGeocodeResult,
  onChooseFavoriteAddress,
  onClearFavoriteAddresses,
  onChooseRecentAddress,
  onClearRecentAddresses,
  onSearchActionKeyDown,
}: BuildHeaderSearchPanelsPropsOptions): AddressSearchPanelProps => ({
  addressInputRef,
  addressQuery,
  geocodeStatus,
  geocodeError,
  geocodeResultsCount,
  activeDistanceLabel,
  locationStatus,
  searchLocationLabel,
  searchAnchor,
  searchActionCount,
  isPinnedFavorite,
  pinnedFavoriteRole,
  favoriteRoleLabels: FAVORITE_ROLE_LABELS,
  favoriteAddresses,
  quickFavoriteAddresses,
  visibleGeocodeResults,
  visibleFavoriteAddresses,
  visibleRecentAddresses,
  favoriteAddressOffset,
  recentAddressOffset,
  registerSearchActionRef,
  onAddressQueryChange,
  onAddressInputKeyDown,
  onAddressSearch,
  onClearAddressSearch,
  onToggleFavoriteAddress,
  onSetFavoriteAddressRole,
  onClearFavoriteAddressRole,
  onChooseGeocodeResult,
  onChooseFavoriteAddress,
  onClearFavoriteAddresses,
  onChooseRecentAddress,
  onClearRecentAddresses,
  onSearchActionKeyDown,
})
