import type { MainWorkspaceProps } from './appPresentationBuilderTypes'
import type { BuildMainWorkspacePropsOptions } from './buildMainWorkspaceTypes'

export const buildMapViewProps = ({
  center,
  segments,
  zones,
  intersectionZones,
  showZones,
  showIntersectionZones,
  crosswalkZones,
  showCrosswalkZones,
  parkingSpaces,
  showParkingSpaces,
  showInferredCandidates,
  selectedId,
  districtBounds,
  districtBoundsKey,
  activeFocusBounds,
  activeFocusCenter,
  recommendedSegmentIds,
  searchLocation,
  searchLocationLabel,
  coverageBoundary,
  paidCurbReferencePoints,
  selectedCenter,
  selectedArrivalKind,
  selectedArrivalLabel,
  recommendedParkingTargetMarkers,
  selectedParkingSpaceMarkers,
  selectedRouteProfile,
  selectedRoutePath,
  userLocation,
  onSelectMapSegment,
  onSelectRecommendedTarget,
  onSelectParkingSpace,
  onPickMapLocation,
}: BuildMainWorkspacePropsOptions): MainWorkspaceProps['mapViewProps'] => ({
  center,
  segments,
  zones,
  intersectionZones,
  showZones,
  showIntersectionZones,
  crosswalkZones,
  showCrosswalkZones,
  parkingSpaces,
  showParkingSpaces,
  showInferredCandidates,
  selectedId,
  districtBounds,
  districtBoundsKey,
  focusBounds: activeFocusBounds?.bounds ?? null,
  focusBoundsKey: activeFocusBounds?.key ?? null,
  focusCenter: activeFocusCenter?.center ?? null,
  focusCenterKey: activeFocusCenter?.key ?? null,
  recommendedSegmentIds,
  searchLocation,
  searchLocationLabel,
  coverageBoundary,
  paidCurbReferencePoints,
  arrivalLocation: selectedCenter,
  arrivalLocationKind: selectedArrivalKind,
  arrivalLocationLabel: selectedArrivalLabel ? `Arrival: ${selectedArrivalLabel}` : null,
  recommendedParkingTargetMarkers: recommendedParkingTargetMarkers ?? [],
  selectedParkingSpaceMarkers: selectedParkingSpaceMarkers ?? [],
  routeProfile: selectedRouteProfile,
  routeGeometry: selectedRoutePath?.geometry ?? null,
  userLocation,
  onSelect: onSelectMapSegment,
  onSelectRecommendedTarget,
  onSelectParkingSpace,
  onPickLocation: onPickMapLocation,
})
