import {
  formatDistanceMeters,
  formatEtaDuration,
  formatParkingSpaceCount,
  formatRecommendationLabel,
  formatRouteDistanceMeters,
  formatWalkDistanceMeters,
} from './displayFormatting'
import { RECOMMENDATION_RANK_MODE_LABELS } from './appPresentationConfig'
import type {
  AddressRecommendationsProps,
} from './buildAddressRecommendationsPropsTypes'
import type { BuildHeaderSearchPanelsPropsOptions } from './buildHeaderSearchPanelsTypes'

export const buildAddressRecommendationsProps = ({
  searchAnchor,
  recommendationRankMode,
  addressRecommendationRankingLabel,
  addressRecommendationFeedbackLabel,
  parkingAnswer,
  parkingAnswerServiceStatus,
  parkingAnswerServiceError,
  parkingCoverageNotice,
  parkingCoverageReferenceState,
  parkingCoverageReferenceAddressLabel,
  parkingAnswerReport,
  nearbySnapshot,
  bestAddressRecommendation,
  bestAddressRecommendationTarget,
  bestAddressRecommendationReason,
  bestAddressRecommendationFeedback,
  bestAddressRecommendationReport,
  bestAddressRecommendationArrivalHint,
  bestAddressRecommendationArrivalKind,
  bestAddressRecommendationWalkDistance,
  bestAddressRecommendationNavigationLinks,
  bestAddressRecommendationRouteEta,
  alternativeAddressRecommendations,
  addressRecommendationEmptyMessage,
  routeEtaStatus,
  routeEtaError,
  routeEtaBySegmentId,
  reportsBySegment,
  navigationOrigin,
  searchLocation,
  selectedId,
  bestRecommendationIndex,
  alternativeRecommendationOffset,
  registerSearchActionRef,
  onSearchActionKeyDown,
  onRecommendationRankModeChange,
  onParkingAnswerReport,
  onSelectAddressRecommendation,
  onSaveBestRecommendationPlan,
  onNavigateToRecommendation,
}: BuildHeaderSearchPanelsPropsOptions): AddressRecommendationsProps => ({
  hasPinnedAddress: Boolean(searchAnchor),
  recommendationRankMode,
  recommendationRankModeLabels: RECOMMENDATION_RANK_MODE_LABELS,
  addressRecommendationRankingLabel,
  addressRecommendationFeedbackLabel,
  parkingAnswer,
  parkingAnswerServiceStatus,
  parkingAnswerServiceError,
  parkingCoverageNotice,
  parkingCoverageReferenceState,
  parkingCoverageReferenceAddressLabel,
  parkingAnswerReport,
  nearbySnapshot,
  bestAddressRecommendation,
  bestAddressRecommendationTarget,
  bestAddressRecommendationReason,
  bestAddressRecommendationFeedback,
  bestAddressRecommendationReport,
  bestAddressRecommendationArrivalHint,
  bestAddressRecommendationArrivalKind,
  bestAddressRecommendationWalkDistance,
  bestAddressRecommendationNavigationLinks,
  bestAddressRecommendationRouteEta,
  alternativeAddressRecommendations,
  addressRecommendationEmptyMessage,
  routeEtaStatus,
  routeEtaError,
  routeEtaBySegmentId,
  reportsBySegment,
  navigationOrigin,
  searchLocation,
  selectedId,
  bestRecommendationIndex,
  alternativeRecommendationOffset,
  registerSearchActionRef,
  formatDistanceMeters,
  formatParkingSpaceCount,
  formatWalkDistanceMeters,
  formatRouteDistanceMeters,
  formatEtaDuration,
  formatRecommendationLabel,
  onSearchActionKeyDown,
  onRecommendationRankModeChange,
  onParkingAnswerReport,
  onSelectAddressRecommendation,
  onSaveBestRecommendationPlan,
  onNavigateToRecommendation,
})
