import type { HeaderPanelsProps } from './appPresentationBuilderTypes'

export type AddressSearchPanelProps = HeaderPanelsProps['addressSearchPanelProps']

export interface BuildAddressSearchPanelPropsOptions {
  addressInputRef: AddressSearchPanelProps['addressInputRef']
  addressQuery: AddressSearchPanelProps['addressQuery']
  geocodeStatus: AddressSearchPanelProps['geocodeStatus']
  geocodeError: AddressSearchPanelProps['geocodeError']
  geocodeResultsCount: AddressSearchPanelProps['geocodeResultsCount']
  activeDistanceLabel: AddressSearchPanelProps['activeDistanceLabel']
  locationStatus: AddressSearchPanelProps['locationStatus']
  searchLocationLabel: AddressSearchPanelProps['searchLocationLabel']
  searchAnchor: AddressSearchPanelProps['searchAnchor']
  searchActionCount: AddressSearchPanelProps['searchActionCount']
  isPinnedFavorite: AddressSearchPanelProps['isPinnedFavorite']
  pinnedFavoriteRole: AddressSearchPanelProps['pinnedFavoriteRole']
  favoriteAddresses: AddressSearchPanelProps['favoriteAddresses']
  quickFavoriteAddresses: AddressSearchPanelProps['quickFavoriteAddresses']
  visibleGeocodeResults: AddressSearchPanelProps['visibleGeocodeResults']
  visibleFavoriteAddresses: AddressSearchPanelProps['visibleFavoriteAddresses']
  visibleRecentAddresses: AddressSearchPanelProps['visibleRecentAddresses']
  favoriteAddressOffset: AddressSearchPanelProps['favoriteAddressOffset']
  recentAddressOffset: AddressSearchPanelProps['recentAddressOffset']
  registerSearchActionRef: AddressSearchPanelProps['registerSearchActionRef']
  onAddressQueryChange: AddressSearchPanelProps['onAddressQueryChange']
  onAddressInputKeyDown: AddressSearchPanelProps['onAddressInputKeyDown']
  onAddressSearch: AddressSearchPanelProps['onAddressSearch']
  onClearAddressSearch: AddressSearchPanelProps['onClearAddressSearch']
  onToggleFavoriteAddress: AddressSearchPanelProps['onToggleFavoriteAddress']
  onSetFavoriteAddressRole: AddressSearchPanelProps['onSetFavoriteAddressRole']
  onClearFavoriteAddressRole: AddressSearchPanelProps['onClearFavoriteAddressRole']
  onChooseGeocodeResult: AddressSearchPanelProps['onChooseGeocodeResult']
  onChooseFavoriteAddress: AddressSearchPanelProps['onChooseFavoriteAddress']
  onClearFavoriteAddresses: AddressSearchPanelProps['onClearFavoriteAddresses']
  onChooseRecentAddress: AddressSearchPanelProps['onChooseRecentAddress']
  onClearRecentAddresses: AddressSearchPanelProps['onClearRecentAddresses']
  onSearchActionKeyDown: AddressSearchPanelProps['onSearchActionKeyDown']
}
