import { useMemo } from 'react'
import {
  buildAppDerivedState,
  type AppDerivedStateOptions,
} from './appDerivedState'

export type { AppDerivedStateOptions, DatasetOption } from './appDerivedState'

export const useAppDerivedState = ({
  actionFilter,
  activeView,
  datasetId,
  datasetMeta,
  datasetOptions,
  defaultRadiusMeters,
  defaultRecommendationRankMode,
  defaultRiskMode,
  defaultRouteProfile,
  defaultSegmentActionFilter,
  filterQuery,
  hideReportedIllegal,
  includeInferred,
  locationLabel,
  markedSpacesOnly,
  mode,
  radiusMeters,
  recommendationRankMode,
  riskMode,
  searchAnchor,
  selectedId,
  selectedParkingSpaceKeyBySegment,
  selectedRouteProfile,
  userLocation,
}: AppDerivedStateOptions) =>
  useMemo(
    () =>
      buildAppDerivedState({
        actionFilter,
        activeView,
        datasetId,
        datasetMeta,
        datasetOptions,
        defaultRadiusMeters,
        defaultRecommendationRankMode,
        defaultRiskMode,
        defaultRouteProfile,
        defaultSegmentActionFilter,
        filterQuery,
        hideReportedIllegal,
        includeInferred,
        locationLabel,
        markedSpacesOnly,
        mode,
        radiusMeters,
        recommendationRankMode,
        riskMode,
        searchAnchor,
        selectedId,
        selectedParkingSpaceKeyBySegment,
        selectedRouteProfile,
        userLocation,
      }),
    [
      actionFilter,
      activeView,
      datasetId,
      datasetMeta,
      datasetOptions,
      defaultRadiusMeters,
      defaultRecommendationRankMode,
      defaultRiskMode,
      defaultRouteProfile,
      defaultSegmentActionFilter,
      filterQuery,
      hideReportedIllegal,
      includeInferred,
      locationLabel,
      markedSpacesOnly,
      mode,
      radiusMeters,
      recommendationRankMode,
      riskMode,
      searchAnchor,
      selectedId,
      selectedParkingSpaceKeyBySegment,
      selectedRouteProfile,
      userLocation,
    ],
  )
