import { useCallback } from 'react'
import {
  applySharedAppStateSnapshot,
} from './sharedAppStateApplyState'
import type {
  SharedAppStateApplyOptions,
  UseSharedAppStateApplyResult,
} from './sharedAppStateApplyTypes'
import type { SharedAppState } from './shareState'

export const useSharedAppStateApply = ({
  defaultRecommendationRankMode,
  defaultRouteProfile,
  defaultRiskMode,
  defaultRadiusMeters,
  cameraRequestIdRef,
  geocodeRequestIdRef,
  routeRequestIdRef,
  selectedRouteRequestIdRef,
  selectedRouteEtaRequestIdRef,
  setDatasetId,
  setFilterQuery,
  setAddressQuery,
  setGeocodeResults,
  setGeocodeStatus,
  setGeocodeError,
  setSearchAnchor,
  setSelectedId,
  setSelectedParkingSpaceKeyBySegment,
  setRecommendationRankMode,
  setSelectedRouteProfile,
  setSelectedRoutePath,
  setSelectedRouteStatus,
  setSelectedRouteError,
  setSelectedTargetRouteEta,
  setRouteEtaBySegmentId,
  setRouteEtaStatus,
  setRouteEtaError,
  setRiskMode,
  setActionFilter,
  setIncludeInferred,
  setMarkedSpacesOnly,
  setHideReportedIllegal,
  setRadiusMeters,
  setMode,
  setNowHHMM,
  setActiveView,
}: SharedAppStateApplyOptions): UseSharedAppStateApplyResult => {
  const makeCameraKey = useCallback(
    (prefix: string) => {
      cameraRequestIdRef.current += 1
      return `${prefix}:${cameraRequestIdRef.current}`
    },
    [cameraRequestIdRef],
  )

  const applySharedState = useCallback(
    (nextState: SharedAppState) => {
      applySharedAppStateSnapshot({
        nextState,
        makeCameraKey,
        defaultRecommendationRankMode,
        defaultRouteProfile,
        defaultRiskMode,
        defaultRadiusMeters,
        geocodeRequestIdRef,
        routeRequestIdRef,
        selectedRouteRequestIdRef,
        selectedRouteEtaRequestIdRef,
        setDatasetId,
        setFilterQuery,
        setAddressQuery,
        setGeocodeResults,
        setGeocodeStatus,
        setGeocodeError,
        setSearchAnchor,
        setSelectedId,
        setSelectedParkingSpaceKeyBySegment,
        setRecommendationRankMode,
        setSelectedRouteProfile,
        setSelectedRoutePath,
        setSelectedRouteStatus,
        setSelectedRouteError,
        setSelectedTargetRouteEta,
        setRouteEtaBySegmentId,
        setRouteEtaStatus,
        setRouteEtaError,
        setRiskMode,
        setActionFilter,
        setIncludeInferred,
        setMarkedSpacesOnly,
        setHideReportedIllegal,
        setRadiusMeters,
        setMode,
        setNowHHMM,
        setActiveView,
      })
    },
    [
      defaultRadiusMeters,
      defaultRecommendationRankMode,
      defaultRiskMode,
      defaultRouteProfile,
      geocodeRequestIdRef,
      makeCameraKey,
      routeRequestIdRef,
      selectedRouteEtaRequestIdRef,
      selectedRouteRequestIdRef,
      setActionFilter,
      setActiveView,
      setAddressQuery,
      setDatasetId,
      setFilterQuery,
      setGeocodeError,
      setGeocodeResults,
      setGeocodeStatus,
      setHideReportedIllegal,
      setIncludeInferred,
      setMarkedSpacesOnly,
      setMode,
      setNowHHMM,
      setRadiusMeters,
      setRecommendationRankMode,
      setRiskMode,
      setRouteEtaBySegmentId,
      setRouteEtaError,
      setRouteEtaStatus,
      setSearchAnchor,
      setSelectedId,
      setSelectedParkingSpaceKeyBySegment,
      setSelectedRouteError,
      setSelectedRoutePath,
      setSelectedRouteProfile,
      setSelectedRouteStatus,
      setSelectedTargetRouteEta,
    ],
  )

  return {
    makeCameraKey,
    applySharedState,
  }
}
