import {
  useSavedPlanSyncActions,
} from './useSavedPlanSyncActions'
import {
  useSavedPlanSaveAndShareActions,
} from './useSavedPlanSaveAndShareActions'
import type {
  UseSavedPlanShareActionsOptions,
  UseSavedPlanShareActionsResult,
} from './savedPlanShareActionTypes'

export const useSavedPlanShareActions = ({
  buildShareUrlForState,
  currentShareUrl,
  currentSavedPlan,
  savedPlans,
  datasetId,
  searchLocationLabel,
  filterQuery,
  recommendationRankMode,
  selectedRouteProfile,
  riskMode,
  mode,
  radiusMeters,
  actionFilter,
  selectedSegment,
  selectedArrivalLabel,
  selectedRouteEta,
  bestAddressRecommendation,
  bestAddressRecommendationTarget,
  bestAddressRecommendationRouteEta,
  savedPlanLimit,
  setReportVersion,
  setSavedPlanConflictDetailsByUrl,
  setSavedPlanConflictSharedByUrl,
  setSavedPlanConflictUrls,
  setSavedPlans,
  setShareStatus,
}: UseSavedPlanShareActionsOptions): UseSavedPlanShareActionsResult => {
  const {
    clearSavedPlanConflictsForUrls,
    handleAutoRefreshSync,
    handleAutoRefreshSyncResources,
    handleAutoRetrySyncWrites,
    handleAutoRetrySyncWritesNow,
    handleRefreshSync,
    handleRefreshResourceSync,
    handleRetryResourceSync,
    handleRetrySyncWrites,
    isRefreshingSync,
    refreshingResources,
    retryingResources,
  } = useSavedPlanSyncActions({
    savedPlans,
    savedPlanLimit,
    setReportVersion,
    setSavedPlanConflictDetailsByUrl,
    setSavedPlanConflictSharedByUrl,
    setSavedPlanConflictUrls,
    setSavedPlans,
    setShareStatus,
  })
  const {
    handleSaveListSegment,
    handleSaveBestRecommendationPlan,
    handleSaveCurrentPlan,
    handleCopyShareLink,
    handleNativeShare,
  } = useSavedPlanSaveAndShareActions({
    buildShareUrlForState,
    currentShareUrl,
    currentSavedPlan,
    savedPlans,
    datasetId,
    searchLocationLabel,
    filterQuery,
    recommendationRankMode,
    selectedRouteProfile,
    riskMode,
    mode,
    radiusMeters,
    actionFilter,
    selectedSegment,
    selectedArrivalLabel,
    selectedRouteEta,
    bestAddressRecommendation,
    bestAddressRecommendationTarget,
    bestAddressRecommendationRouteEta,
    savedPlanLimit,
    setSavedPlans,
    setShareStatus,
    clearSavedPlanConflictsForUrls,
  })

  return {
    handleSaveListSegment,
    handleSaveBestRecommendationPlan,
    handleSaveCurrentPlan,
    handleCopyShareLink,
    handleAutoRefreshSync,
    handleAutoRefreshSyncResources,
    handleAutoRetrySyncWrites,
    handleAutoRetrySyncWritesNow,
    handleRefreshSync,
    handleRefreshResourceSync,
    handleRetryResourceSync,
    handleRetrySyncWrites,
    handleNativeShare,
    isRefreshingSync,
    refreshingResources,
    retryingResources,
  }
}
