export const BUS_STOP_BUFFER_METERS = 10
export const HYDRANT_BUFFER_METERS = 5
export const INTERSECTION_NO_STOP_M = 8
export const CROSSWALK_BUFFER_METERS = 6
export const ZONE_PARAMS_VERSION = `bus-${BUS_STOP_BUFFER_METERS}-hydrant-${HYDRANT_BUFFER_METERS}-intersection-${INTERSECTION_NO_STOP_M}-crosswalk-${CROSSWALK_BUFFER_METERS}-v1`
